# WhatATheme
markdown: kramdown

# URL of the Site
url: ""
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Dai Tran
# Description of the Site
description: An agile continuous learning Security as Code enabler
# URL of Image of the Site
site-image: assets/images/white_hat_hacker.jpg
# Keywords of the Site
site-keywords: Dai Tran, Portfolio, Blog, Cyber Security, Automation
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: /assets/images/homepage-background-man-sunrise.jpg
heroimage: /assets/images/homepage-background-wollong3.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: spmkeeper@gmail.com
facebook_username:
twitter_username: ''
instagram_username:
linkedin_username: trantdai
github_username: trantdai
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Dai Tran
# URL for the Image of the Author
author-image: /assets/images/author_dai-tran-linkedin.jpg
# 60 Words About the Author
author-about: Highly motivated research oriented Computing and Communications PhD graduate with extensive cross-domain engineering experience comprising of over 11 years work experience in multiple domains of Network Security, Cyber Security , DevOps, and automation solution development with a proven track record of success delivering complicated security architecture, design, development, and implementation. Driving improvements in processes, operational efficiency/agility and system stability in complex large-scale mission-critical environments across diverse industries including Financial, IT, Travel, Food and Beverage, and Education services. Skilled in multi-vendor firewall migration and administration, Cyber/Cloud Security automation, security technology REST APIs, Infrastructure as Code (Terraform/Terratest), Python secure software development, Linux, Bash scripting, Ansible/Tower, Security as Code, Docker, CI/CD and DevSecOps tools/methodologies.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://trantdai.github.io/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
